name: Build
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  gradle:
    strategy:
      matrix:
        jdk: [8, 11]
        experimental: [false]
        include:
          - jdk: 17
            experimental: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
    continue-on-error: ${{ matrix.experimental }}
